version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ADD_DIRECTORY_NAME_HERE
permissions:
  - object: /var/www/ADD_DIRECTORY_NAME_HERE
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/build.sh
      timeout: 3600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu